# Generated by Django 5.1.8 on 2025-07-16 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elder_services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elder_services.user_info', verbose_name='User Name'),
        ),
    ]
