# Generated by Django 5.1.8 on 2025-07-16 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elder_services', '0002_alter_bookings_price_alter_bookings_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='booking_time',
            field=models.DateTimeField(verbose_name='Booking Time'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='from_date',
            field=models.DateField(verbose_name='From Date'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='service_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elder_services.services', verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='subservice_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elder_services.sub_services', verbose_name='Subservice'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='to_date',
            field=models.DateField(verbose_name='To Date'),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_name',
            field=models.CharField(max_length=50, verbose_name='Service Name'),
        ),
        migrations.AlterField(
            model_name='sub_services',
            name='subservice_name',
            field=models.CharField(max_length=100, verbose_name='Subservice Name'),
        ),
    ]
